// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wCE7BfK9s4lGNjZc7HRl0hTtSXmjnQ0',
    appId: '1:779693137178:web:bdeb5b7a37d04bc5f160a3',
    messagingSenderId: '779693137178',
    projectId: 'the-hunting-party-app',
    authDomain: 'the-hunting-party-app.firebaseapp.com',
    storageBucket: 'the-hunting-party-app.firebasestorage.app',
    measurementId: 'G-YZLQP0S9PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCciX2fOnKbOSdY1nI17PEkT2eTDPRjjWQ',
    appId: '1:779693137178:android:ff08a0b3a16295b3f160a3',
    messagingSenderId: '779693137178',
    projectId: 'the-hunting-party-app',
    storageBucket: 'the-hunting-party-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvVBVq_coulsZ9QH6b5WdjZYwbAW1iYA',
    appId: '1:779693137178:ios:a3e0f62338800db8f160a3',
    messagingSenderId: '779693137178',
    projectId: 'the-hunting-party-app',
    storageBucket: 'the-hunting-party-app.firebasestorage.app',
    iosBundleId: 'com.example.theHuntingParty',
  );
}
